### PR TITLE
NO-ISSUE: Fix shellcheck complaints

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Comment by zaneb** [comment]
This code doesn't actually cause any problems, but must be changed to allow shellcheck to run on these files (in https://github.com/openshift/release/pull/58429). Therefore, skipping Jira ticket check.
/retitle: NOISSUE: Fix shellcheck complaints

**Comment by dtantsur** [comment]
/override ci/prow/okd-images

This change has nothing to do with image building.

**Pull request merged**
